### PR TITLE
Syntax highlighting

### LINKED ISSUE #1382: Syntax highlighting quirks in code snippets
We use codefencing in markdown and [highlight.js](https://highlightjs.org/) for syntax highlighting. Highlight.js seems to guess the syntax, and seems to guess wrong a lot.

Here are [two indented code blocks](https://cloud.gov/docs/getting-started/concepts/#buildpacks). Both should be yaml but one is being detected as vimscript:
screenshot from 2019-01-31 17-17-23

I propose dropping highlight.js and just using Hugo's built-in [Pygments/Chroma](https://gohugo.io/content-management/syntax-highlighting/) support.

### PR DESCRIPTION
**Pull request by adborden**
Fixes #1382

Replaces highlight.js with Hugo's built-in Pygments/Chroma support.

### CODE REVIEW

**Comment by rogeruiz** [comment]
Hey @adborden, can you rebase and I’ll run the CI tests so we can get this in? Thanks!

**Review by rogeruiz — APPROVED** [review]
:shipit:

**Comment by adborden** [comment]
@rogeruiz looks like the branch is up to date now. Anything else you need from me?

**Comment by rogeruiz** [comment]
nah, thanks @adborden

**Pull request merged**
