### PR TITLE
Fixing issues with dependencies

### PR DESCRIPTION
**Pull request by mheadd**
## Changes proposed in this pull request:
- Update Node.js dependencies with security issues.
- Remove unsupported `a11y` module.
- [Future change](https://github.com/cloud-gov/cg-site/issues/1748) will add `pa11y` for accessibility checks.

## Security Considerations
Update dependencies with known security issues.

### CODE REVIEW

**Comment by mheadd** [comment]
Still one issue remaining unresolved.

```
                      === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ dot-prop                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.1.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ a11y [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ a11y > update-notifier > configstore > dot-prop              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1213                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 738 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```

**Comment by mheadd** [comment]
So, `a11y` seems  to be archived and not currently maintained. Any objection to removing it as a dependency? Not sure the `npm run test` command is being run in any automated way. We could replace it with something else that does a similar check, but if `a11y` is unmaintained, we're going to keep running into dependency issues. Thoughts @apburnes?

**Comment by ccostino** [comment]
I thought I saw a PR go through with a switch to pa11y, but can't find it; was I seeing things?

**Comment by onelittlebecca** [comment]
I saw that PR @ccostino but not sure where it is...

**Comment by mheadd** [comment]
@ccostino @onelittlebecca Looks like @apburnes mentions it [here](https://github.com/cloud-gov/cg-site/pull/1747#issuecomment-672176658).

**Comment by apburnes** [comment]
Kept the kramdown specific to the kramdown update.  Here's a pa11y issue i created https://github.com/cloud-gov/cg-site/issues/1748.

**Comment by mheadd** [comment]
Removed `a11y` to ensure that nothing breaks.

**Review by apburnes — APPROVED** [review]

**Pull request merged**
