### PR TITLE
[WIP] Drop manual aws mfa check in favor of automated check.

### PR DESCRIPTION
**Pull request by jmcarp**
Goes with https://github.com/18F/cg-deploy-prometheus/pull/41.

### CODE REVIEW

**Review by pburkholder — APPROVED** [review]
Woot!

**Comment by brittag** [comment]
This will be great! We just can't merge this until Prometheus and the related alert are in production. (I know you all know that, just noting it for clarity.)

**Comment by brittag** [comment]
@jmcarp This is ready to merge since this is running in production, right? (Checking since it's labeled WIP.)

**Review by brittag — APPROVED** [review]
This alert is in production, going to just merge.

**Pull request merged**
