### PR TITLE
Sunset outdated pricing content

### PR DESCRIPTION
**Pull request by karareinsel**
## Changes proposed in this pull request:
- Removed outdated pricing content
-
-

## security considerations
NA -  this is content only

### CODE REVIEW

**Review by hillaryj — DISMISSED** [review]
LGTM

**Comment by mheadd** [comment]
The page removed in this PR `start-using-cloudgov.md ` is linked to in a few different places in the site, so the build is breaking. I can remove most of them without issue, but there are a few links to that deleted page on the site home page. I can replace them easily, which will let the build finish, but wanted to ask @karareinsel for thoughts on what to replace the links with before doing so.

**Comment by mheadd** [comment]
@hillaryj @karareinsel  I removed all of the outdated links to the deleted pages, and replaced them with Kara's suggestions. The build issue is resolved, but you may want to verify in the Federalist preview, particularly the changes to the home page.

**Comment by mheadd** [comment]
@karareinsel I just noticed that the link to the Federalist preview is in the PR. If you click on `Show all checks` below 👇  you'll see a link to the preview. That's pretty slick.

**Review by mheadd — APPROVED** [review]
Ready to merge.

**Pull request merged**
