### PR TITLE
Document ephemeral sandbox policy.

### PR DESCRIPTION
**Pull request by jmcarp**
Document notification and purging behavior implemented in https://github.com/18F/cg-sandbox/pull/5.

Note: I'm guessing we'll want to make this notice more prominent so that users don't miss it.

### CODE REVIEW

**Comment by mogul** [comment]
@khandelwal is saying he thinks this should be 90 days rather than 30, btw.

**Review by mogul — DISMISSED** [review]
Looks good to me. We should probably merge this now even though the actual clock hasn't started so that people creating sandboxes will know about the policy up front. What do you think @brittag ?

**Comment by brittag** [comment]
@mogul I don't think we should merge this exact change until we actually implement the policy, since I don't know how long it'll be before we can ship this feature (since it has an external dependency on the TRs). We could ship it with a "Note: this is coming soon but not happening yet" thing.

**Review by gboone — DISMISSED** [review]

**Review by mogul — CHANGES_REQUESTED** [review]
I'll approve and merge this as soon as it's brought up to date with master.

**Comment by jmcarp** [comment]
Rebased.

**Review by mogul — DISMISSED** [review]

**Comment by mogul** [comment]
Looks like maybe it needs to be rebased again...?

**Review by mogul — APPROVED** [review]

**Pull request merged**
