### PR TITLE
Add 18F open source policy note to repos page

### PR DESCRIPTION
**Pull request by brittag**
Giving more context to our open source work, so people can easily find our rationale.

### CODE REVIEW

**Review by nikzei — COMMENTED** [review]
Is cloud.gov technically part of 18F? Or is it separate (we have a separate P+L) but staffed by an 18F team? 

If we're not clear, another option is to leave out any discussion of us being part of 18F and to just say , "to learn more about why we an open source project, read the [18F open source policy], which has guided our work."

**Comment by brittag** [comment]
@nikzei Good question, relevant for https://github.com/18F/cg-site/pull/719 and other docs as well! We could define this in several ways - organizationally, financially, etc. - so the important thing is to be consistent. I updated this to match the existing language at [Overview](https://cloud.gov/overview/), [What is cloud.gov](https://cloud.gov/overview/overview/what-is-cloudgov/), and [Why 18F built it](https://cloud.gov/overview/overview/why-build-cloudgov/) - that cloud.gov is built and maintained by 18F.

**Comment by adborden** [comment]
:+1: that is also consistent with the dashboard footer.
screenshot from 2017-01-27 16-11-11

**Comment by brittag** [comment]
Ha you're right, thanks @adborden!

**Review by nikzei — APPROVED** [review]

**Pull request merged**
