### PR TITLE
Added instructions, how to add different OAuth client, and how to use it in CI pipelines to obtain long lived tokes

### PR DESCRIPTION
**Pull request by s-matyukevich**

### CODE REVIEW

**Comment by mogul** [comment]
@brittag can you put :eyes: on this one?

**Comment by mogul** [comment]
We don't want to manage the complexity of our users having to use a special version of the CLI, so this one is blocked on the acceptance of the CLI change upstream. (Also the repositories it points to for the plugin, etc. should be moved to the 18F org.)

**Comment by jmcarp** [comment]
Are we still planning to handle deployer accounts like this @LinuxBozo @mogul? I have a vague memory of the UAA team planning work on persistent tokens, but maybe I dreamed it.

**Comment by brittag** [comment]
(I removed my assignment from this since it seems to need additional technical decision-making before I should look over it from a content perspective - feel free to re-assign me when I can be helpful for this. :))

**Comment by mogul** [comment]
> Are we still planning to handle deployer accounts like this @LinuxBozo @mogul? I have a vague memory of the UAA team planning work on persistent tokens, but maybe I dreamed it.

That's correct. I'm going to close this one as we won't be pursuing this path.

**Pull request closed without merging**
