### PR TITLE
Adding system boundary diagram for reference

### PR DESCRIPTION
**Pull request by brittag**
Uploading our system diagram that explains our FedRAMP authorization boundary, so that it's easily available for reference in a handy public spot.

### CODE REVIEW

**Comment by brittag** [comment]
P.S. Crediting @LinuxBozo for the most recent diagram update, thanks!

**Comment by afeld** [comment]
Can we embed it on some page? Seems easy to lose track of otherwise.

**Comment by afeld** [comment]
...with a comment about where to find the ~~original~~ source.

**Comment by brittag** [comment]
Good point; I'm going to close this for now until we decide a few more things about this (ref #cloud-gov-highbar).

**Pull request closed without merging**
