### PR TITLE
Clarify how to find an organization's quota

### PR DESCRIPTION
**Pull request by fureigh**
Per https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1497282441267790.

Ready for review.

### CODE REVIEW

**Comment by brittag** [comment]
Thanks Fureigh! This is running into the same issue as https://github.com/18F/cg-site/pull/910 - the practical info for users should be in /docs rather than /overview, but we don't really have a page there for org managers. I think both of these issues could be solved together.

**Comment by fureigh** [comment]
@brittag Ah, thanks for drawing my attention to that one! I'm inclined to merge this and tackle the larger issue in a separate PR — how does that sound to you?

**Comment by brittag** [comment]
@fureigh That sounds good to me, thanks!

**Comment by fureigh** [comment]
@brittag 🆒, thanks! Merging is currently blocked; can you ✅ via GitHub's pull request UI?

(Not a blocker, but @jeremiak, when you have a moment, I'd love your feedback on whether these instructions would've adequately addressed the issue.)

**Comment by fureigh** [comment]
@brittag I removed the client-facing part, per our conversation. Ready for another look.

**Comment by brittag** [comment]
I'm sort of confused since the remaining bit is in the team-facing documentation, not in user-facing documentation; it doesn't hurt to have this info in team-facing docs, but the user-facing need is still there (and I think it needs the work in https://github.com/18F/cg-site/pull/910 in order to have a good place to live)...

**Comment by fureigh** [comment]
@brittag Wasn't @jeremiak's initial bug report about the team-facing documentation? https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1497282441267790

**Comment by brittag** [comment]
I don't think so...I think he's asking about this from an Org Manager perspective instead of a Platform squad perspective. 🤔

**Comment by fureigh** [comment]
Expanding the scope of this PR will exceed our time threshold for white-noise work, so I added a Favro card, [Create org manager section of the docs](https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-5865), for the documentation reorganization work @brittag's identified here and in #910.

**Comment by jmcarp** [comment]
Did we decide to merge this and do other work in a separate PR, or to close this and do other work in a separate PR? @fureigh @brittag

**Comment by brittag** [comment]
Closing this one since the team docs don't need this change; https://github.com/18F/cg-site/pull/910 is closer to what I think we need to do (in user-facing material).

**Pull request closed without merging**
