### PR TITLE
Adds platform release notes for past two sprints.

### PR DESCRIPTION
**Pull request by berndverst**
The first of bi-weekly technical release notes.

Available at `/updates/2016-11-18-release-notes/`

Working doc:
https://docs.google.com/document/d/1Km3z2H8aH3wN-j2RguobNUhWdV7Hngu6AxwC6SHLbW8/edit#

Context:
https://gsa-tts.slack.com/archives/cloud-gov/p1479499329003075

image

### CODE REVIEW

**Comment by brittag** [comment]
YAY. Wrote some suggested revisions in the Google doc (https://docs.google.com/document/d/1Km3z2H8aH3wN-j2RguobNUhWdV7Hngu6AxwC6SHLbW8/edit#) since that seemed more efficient than PRing on this PR. :)

**Comment by mogul** [comment]
I really like the changes Britta's proposed to the Google Doc. Separately, I'm raising up assorted security and deprecation points from the Cloud Foundry release notes there.

**Comment by mogul** [comment]
(Done with that now; feel free to change wording if you think it's needed.)

**Comment by berndverst** [comment]
image

**Comment by berndverst** [comment]
Thanks for the edits @brittag. Thanks for the security items @mogul. I think we are good to merge this now!

Feel free to review and do so.

**Review by mogul — APPROVED** [review]

**Pull request merged**
