### PR TITLE
[WIP] add a page for getting people started with the platform

### PR DESCRIPTION
**Pull request by afeld**
Corresponds to ~~https://trello.com/c/IZbvmwPE/401-add-a-walkthrough-for-new-cloud-gov-users~~ https://trello.com/c/nPWMtNlK/580-add-a-walkthrough-for-new-cloud-gov-users.

This page started out as [an outline for live training](https://docs.google.com/document/d/1N0VQf5y0ZeO-9BS0Xk1W2p-YetF7HUqzSB4D-Kj7MXw/edit). I'm happy with the flow of having them go through the [CF Hello Worlds](https://github.com/18F/cf-hello-worlds#readme), though it needs:
- [ ] A narrative walkthrough
- [ ] Move in useful content from linked notes documents
- [ ] Move non-first-run content to other pages

Will continue adding to this checklist.

/cc @ultrasaurus @meiqimichelle #65

### CODE REVIEW

**Comment by afeld** [comment]
@sharms Have you talked with @mogul yet about a first cloud.gov task to pick up? If not, and if you don't mind writing, following through with this pull request might be a good one, since (as I remember) you're coming to Cloud Foundry fresh. What do you think?

**Comment by afeld** [comment]
Some background:

In my recent interviews with members of the cloud.gov team, multiple people pointed out a big hole in our cloud.gov documentation, where we don't really lead people through deploying something to Cloud Foundry for the first time. This page aims to address that need.

I know there are many people in the org that are interested in learning more about Cloud Foundry but never went through a training, so we have plenty of people to test out this guide when it's ready.

**Comment by mogul** [comment]
Thanks for picking that card up! I understand that the WIP is just based on your training notes, but I wanted to get a sense of the intended role of the document... It sounds like you're going to address the third AC ("The online doc indicates how users should proceed to get started using cloud.gov") by expanding the "Deploying" section... Is that right?  That's fine, but just know that it'll only cover the third AC. 

The doc we want to point to needs to really focus on the new user experience... Acknowledge that they just confirmed their account, say something about sandboxes (in particular the fact that they're supplied automatically for .gov and .mil addresses, but not others, and that they're limited to a small quota to keep our expenses in line, and may be time-limited in future). We'll also need to tell contractors that they explicitly _don't_ get sandboxes, and need to get added to orgs by their agency partners. 

Having written that, I'm thinking now that "your first deploy" belongs as a standalone document, and the "welcome to your cloud.gov account" doc needs to be a separate one that refers to it. What do you think?

**Comment by afeld** [comment]
@mogul All of that makes sense. Split the walkthrough part out to https://trello.com/c/nPWMtNlK/580-add-a-walkthrough-for-new-cloud-gov-users.

**Comment by dlapiduz** [comment]
Is this still WIP? @afeld

**Comment by afeld** [comment]
Well, it's certainly incomplete, but if you are game to merge it sooner than later and work on it in smaller chunks, that's fine by me!

**Pull request merged**
