### PR TITLE
Removing Compliance Toolkit description

### PR DESCRIPTION
**Pull request by nikzei**
Edit intended to shift focus of this page to only the services that we are actively offering to customers. 

 When discussing the toolkit, it would be more accurate to describe this as separate from our main offering, and something that the open control community maintains (rather than something that we maintain ourselves).

### CODE REVIEW

**Comment by afeld** [comment]
Going to defer to @mogul on this.

**Comment by brittag** [comment]
We also mention the toolkit in a couple other places: https://github.com/18F/cg-site/search?utf8=%E2%9C%93&q=toolkit - not sure if those should be updated as well.

**Comment by nikzei** [comment]
Thanks for that. And the goal here isn't to leave out any mention of the toolkit so much as to make our communications about our offerings accurate. @jameshupp and @brittag - throwing this in your court!

**Comment by brittag** [comment]
I started looking into this to make the compliance information in the intro docs reflect what we offer (including reducing the emphasis on Compliance Toolkit), but it looks like I'd run into a bunch of conflicts with the PR at https://github.com/18F/cg-site/pull/632 - so it looks like I should set this aside until that gets merged.

**Comment by nikzei** [comment]
PI8 75% assessment:
SHOULD
--> this is directly related to our work this PI on making communications about our product clearer on the website.

**Comment by brittag** [comment]
Filed a new PR that includes a fix for this: https://github.com/18F/cg-site/pull/669

**Pull request closed without merging**
