### PR TITLE
link to the Copy plugin

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by brittag** [comment]
I'd love for this to be stated as more direct guidance if we can. For example, what are cases where the copy plugin helps, and what are cases where it won't help? How can the reader figure out if the manual steps are required?

**Comment by afeld** [comment]
I haven't actually used it, so couldn't say 😛

**Comment by jmcarp** [comment]
I'm thinking we should either figure out how the plugin works so that we can describe it, or not mention it. Saying "here's a thing ymmv" could be confusing.

**Comment by afeld** [comment]
Fair point - won't bother right now then.

**Pull request closed without merging**
