### PR TITLE
TLS update: s2n defeats lucky13

### PR DESCRIPTION
**Pull request by pburkholder**
## Changes proposed in this pull request:
-
- Clarify our use of "older" ciphers
- Note that the s2n TLS implementation mitigates LUCKY13
-

## Security Considerations
Good info for assessors

### CODE REVIEW

**Review by cweibel — DISMISSED** [review]
Clarifications around TLS scans

**Comment by pburkholder** [comment]
@cweibel I tried to shim in one more change. Can you approve?

**Review by ChrisMcGowan — APPROVED** [review]
Changes around TLS info

**Comment by ChrisMcGowan** [comment]
@pburkholder :shipit:

**Pull request merged**
