### PR TITLE
Update identity provider list

### PR DESCRIPTION
**Pull request by mogul**
NSF is no longer registered as an IdP, but many other agencies are.

## Changes proposed in this pull request:
- Remove NSF
- Add many others

## Security Considerations
[Note the any security considerations here, or make note of why there are none]

None, this is just a documentation update; the list of IdPs is already on the login page.

### CODE REVIEW

**Comment by mogul** [comment]
Note that the directions [here](https://github.com/mogul/cg-site/blob/patch-15/_docs/getting-started/accounts.md) should also remove NSF, and account (hah!) for the other IdPs in the list somehow. I don't know what restrictions there are/aren't, so I didn't try to do that here.

**Review by bengerman13 — APPROVED** [review]

**Comment by markdboyd** [comment]
@mogul I'm not sure if we should explicitly list all the integrated providers. The list will always be changing and it seems like it will lead to perpetual documentation rot

**Comment by mogul** [comment]
Up to you, I was just trying to unrot it.

**Comment by markdboyd** [comment]
@mogul I'm going to opt to remove the explicit agency references instead. See #2512. Thanks for bringing this to our attention!

**Pull request closed without merging**
