### PR TITLE
Add MAX.gov account and remove GitHub account requirements in Pages customer responsibilities

### PR DESCRIPTION
**Pull request by svenaas**
Changes to Pages customer requirements.

## Changes proposed in this pull request:
- Document MAX.gov account requirement with links to resources (addresses cloud-gov/pages-core#4060)
- Remove section asserting that Pages requires login with a GitHub account.

:sunglasses:[PREVIEW URL](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/add-max-gov-to-pages-customer-responsibilities)

## Security Considerations
None. This is a website content change.

### CODE REVIEW

**Comment by drewbo** [comment]
@svenaas can we edit rather than remove the GitHub section? Most of the information there, other than the title, is still true and relevant

**Comment by svenaas** [comment]
@drewbo How's this? Do we still require 2FA or should we reduce that to a strong recommendation?

**Comment by drewbo** [comment]
cc: @apburnes for more knowledge; I don't think we require 2FA for Github since we don't use it for Authentication now but I'm not 100% sure. Otherwise this looks good

**Review by drewbo — DISMISSED** [review]

**Comment by apburnes** [comment]
When we were using the federalist-users GitHub org to manage users, we where able to enforce 2FA by making that a requirement for joining the org. Going forward, I don't believe we can enforce it through our Pages OAuth app but maybe we should do some research to see if there are possibilities to enforce 2FA.

**Comment by svenaas** [comment]
I'll look around.

**Comment by svenaas** [comment]
I'm not seeing positive signs that we can do that. I'll amend that text a bit.

**Review by apburnes — APPROVED** [review]

**Pull request merged**
