### PR TITLE
Add pending s3 change to updates

### PR DESCRIPTION
**Pull request by jontours**

### CODE REVIEW

**Comment by rogeruiz** [comment]
Getting the following error  `Error: Cannot find module 'acorn'` during the build.

**Comment by jontours** [comment]
Yeah, I'm looking into it.

**Comment by jontours** [comment]
@rogeruiz I noticed that cg-style was updated.  Is there a chance that is breaking the build?

**Comment by jontours** [comment]
Disregard.  I'm pretty npm _challenged_.  I'm not sure why this dependency needs to now be added.  But the build is fixed.  Ready to merge.

**Review by rogeruiz — APPROVED** [review]
:shipit:

**Pull request merged**
