### PR TITLE
Ask people interested in Windows to email us

### PR DESCRIPTION
**Pull request by brittag**
On the page where we explain that we don't support Windows, encourage readers to email us if they're interested in Windows. This may help us gauge interest.

### CODE REVIEW

**Review by mogul — APPROVED** [review]
It could use a default subject line in the mailto link, but is a marked improvement regardless.

**Comment by brittag** [comment]
@mogul I'm inclined to leave the subject line blank so that people have to write their own, so that we don't have a hundred emails titled "cloud.gov inquiry" in the same thread in email clients. I don't have a strong opinion about it, that's just a benefit to leaving it blank.

**Comment by mogul** [comment]
Fine by me, we may just end up with a hundred emails with a blank subject line instead. ;)

**Comment by khandelwal** [comment]
If we have 100 inquiry emails we'll be so excited, we won't care about the blank subject lines. Besides, we can just make @brittag read them all.

**Pull request merged**
