### PR TITLE
Release notes for 2016-11-30

### PR DESCRIPTION
**Pull request by berndverst**
image

### CODE REVIEW

**Comment by msecret** [comment]
In one place, you mention dashboard as "the dashboard" with link and in another you mention it as "Dashboard: ". Did you have a reason for that?

**Comment by berndverst** [comment]
In the **fixed** section it is nice to just scan for the component / area that one is using which was updated.
I prefer "**Component**: Fix", or adding a sub section if there are multiple fixes corresponding to that component.

However in the **added** section, given the lack of other content I chose to mention dashboard in line. This is also what we did last time.

**Review by msecret — APPROVED** [review]
LGTM

**Comment by berndverst** [comment]
PR has been updated.

image

**Comment by berndverst** [comment]
One more tweak:

image

**Pull request merged**
