### PR TITLE
Add max width class to page layout container

### PR DESCRIPTION
**Pull request by apburnes**
Align left with header for non documentation pages without side navigation elements.

## Changes proposed in this pull request:
- Add max width class desktop to page layout
- Change layout template for home, posts, pricing, and support package pages
- Clean up spacing on affected pages

:sunglasses:[PREVIEW URL](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/apb-adjust-page-width/)

## Security Considerations
- none

### CODE REVIEW

**Comment by bengerman13** [comment]
looks like the "Getting Started" page still doesn't align the logo and content. Otherwise, looks good to me

**Comment by apburnes** [comment]
Thanks @bengerman13. Updated [getting started](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/apb-adjust-page-width/sign-up/)

**Review by bengerman13 — APPROVED** [review]

**Comment by bengerman13** [comment]
LGTM - I think we should get sign-off from @eddietejeda or @karareinsel before merging, though

**Comment by apburnes** [comment]
Oops

**Comment by karareinsel** [comment]
Looks good.

**Pull request merged**
