### PR TITLE
Add guidance for specifying redirect_uri in UAA OAuth requests

### LINKED ISSUE #630: Include how to have multiple callback urls for a registered UAA OAuth client
The [Leveraging Authentication](https://github.com/18F/cg-site/blob/master/content/docs/apps/leveraging-authentication.md) page should include information on how multiple callbacks can be registered with a single UAA OAuth client. This should include information on the `redirect_uri` parameter.

### PR DESCRIPTION
**Pull request by jseppi**
`redirect_uri` must be set when an app has multiple registered UAA OAuth callback URLs.

closes #630

### CODE REVIEW

**Comment by brittag** [comment]
This looks good to me from a content perspective! I'll leave technical review to another person.

**Comment by cnelson** [comment]
The `redirect_uri `can contain [wildcards using Ant-style path pattern matching](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html) so you can do things like `https://*.some.app/` or `https://some.app/**/callback`.  We may want to mention this in our documentation.

**Comment by mogul** [comment]
@cnelson want to take a stab at amending this then?

**Comment by jmcarp** [comment]
Ping @cnelson @mogul

**Comment by cnelson** [comment]
As we've learned, this redirect matching now has a bunch of barely documented rules in it about how many levels deep you are allowed to match, so I don't think it's worth confusing users with. You can ignore my comment above.

**Comment by jseppi** [comment]
Still relevant or should this be closed out?

**Review by mogul — DISMISSED** [review]

**Review by mogul — APPROVED** [review]

**Comment by mogul** [comment]
Still relevant! Sorry this got lost in the noise. Once Concourse and Code Climate report in, I'll merge it.

**Comment by jseppi** [comment]
Thanks, @mogul! Hope all is well over there!

**Pull request merged**
