### PR TITLE
Cloud.gov documentation search integration

### PR DESCRIPTION
**Pull request by juliasolorzano**
This pull request is the continuation of the work started in [this pull request](https://github.com/18F/cg-style/pull/64) (thank you @jcscottiii!). Below is the comp provided by @thisisdano on how the layout and interaction should function.

The integration of search styles are also [started here](https://github.com/18F/cg-style/pull/136) and will be directly effected by the completion of this work.

cc0cee96-7026-11e6-8c01-741ac1cbc222

### CODE REVIEW

**Comment by juliasolorzano** [comment]
During Liberator sprint review today @vz3 requested that the hamburger menu be removed from the side navigation on cloud.gov docs and the search results page. Adding a note about this here. Also, see screenshots below for reference:

## Docs side nav

docs_cloud_gov

## Docs search results

pricing_-_cloud_gov_search_results

**Comment by juliasolorzano** [comment]
Just looked into the search results page and it looks like the hamburger menu is not something we can customize @vz3 😢

**Comment by afeld** [comment]
Not having search in our docs is a constant pain point for me (and surely others)...just another small plug for making "the smallest change that works", then iterating. Thanks for all the hard work on this!

**Comment by thisisdano** [comment]
I'm very comfortable getting this out soon and finessing as we go.

**Comment by vz3** [comment]
yeah I would like for my requests to not be a blocker for getting the search box in.

**Comment by juliasolorzano** [comment]
@afeld @thisisdano @vz3 ^5 - onward! 🚀

**Comment by mogul** [comment]
Soooo... is this all that remains to get search out there?

**Comment by juliasolorzano** [comment]
@mogul UPDATE! My PR for the styles and functionality for this have been merged into `cg-style` (thanks @msecret 🎉 ) [here](https://github.com/18F/cg-style/pull/136). Once this PR is merged in, we should do a design review to make sure it's 👍  with @vz3 @thisisdano.

**Comment by msecret** [comment]
@juliaelman does this need a cg-style release to merge? That's in the works right now

**Comment by juliasolorzano** [comment]
@msecret this PR needs to be merged in first https://github.com/18F/cg-style/pull/159

**Pull request merged**
