### PR TITLE
Some guidance on using Oracle DB

### PR DESCRIPTION
**Pull request by pburkholder**
Replaces #1319, as I don't have branch push access.

### CODE REVIEW

**Review by siennathesane — CHANGES_REQUESTED** [review]
Looks great, I like how comprehensive it is. Can you please update the service access steps to include using Cloud Foundry Service Keys? That's the preferred way of accessing services.

https://docs.cloudfoundry.org/devguide/services/service-keys.html

**Comment by pburkholder** [comment]
Paging @eddietejeda -- good to go?

**Comment by pburkholder** [comment]
@mxplusb As suggested, switched to service keys.

**Review by siennathesane — APPROVED** [review]
LGTM.

**Pull request merged**
