### PR TITLE
Added announcement page in the event of a shutdown

### PR DESCRIPTION
**Pull request by femmebot**
Used content from this repo: https://github.com/18F/cf-ex-staticfile

screencapture-localhost-1313-announcement-1516633259231

### CODE REVIEW

**Comment by mogul** [comment]
We should be advising that they deploy the static app first, remap the route, and then stop their existing app.

**Comment by pburkholder** [comment]
@mogul In this case I disagree. People trying to shutdown this a.m. probably aren't worried about a few minutes of downtime. I'd rather have them get it working with fewer steps, then run into snags or have to open support requests.

**Comment by pburkholder** [comment]
How about we move this to docs/apps/staticsite and just publish as a regular site update?

**Comment by brittag** [comment]
Please do not merge this until approved by Shashank or me, so we can ensure it is aligned with org comms.

**Comment by mogul** [comment]
@pburkholder it's not more steps to do it with zero downtime. They just push the static app with no-route, map-route to it, then unmap-route from the original app.

**Comment by pburkholder** [comment]
Let's close this P.R. and come back to it if there's another, longer shut down.

**Pull request closed without merging**
