### PR TITLE
[WIP] Document high-availability elasticsearch plans.

### PR DESCRIPTION
**Pull request by jmcarp**
Not ready for merge until we finalize the details of the HA plans.

This probably needs a post in `/updates`, and we might want to announce this at the same time as the HA redis service.

cc @cnelson @rogeruiz @mogul @brittag

### CODE REVIEW

**Comment by brittag** [comment]
This looks pretty good! For the note up top about backups, do you think it needs to be super up front? (In other words, does this break people's normal expectations of what an Elasticsearch service should do, so they need to know about it first?)

If it's relatively normal information, I'd recommend moving that information below into the "body" of the documentation (probably under "Managing backups"), so that people can read it in context when they're learning about the service capabilities and options.

**Comment by cnelson** [comment]
I think we should call this `Beta` and maybe still make it free.  We should have some customers running these in production for a few months without issue before we call it GA.

**Comment by mogul** [comment]
:thumbsup:

**Comment by jmcarp** [comment]
Updated to call the service beta, and to move the note about backups to the backups section. This is still `[WIP]` until we sort out plans.

**Comment by brittag** [comment]
@jmcarp Should this PR also remove Elasticsearch from https://cloud.gov/docs/apps/experimental/services/ ?

**Comment by brittag** [comment]
I see a couple copyediting things here but not sure if this is ready for copy-level edits or if there's more to be done here first; feel free to reach out when ready!

**Comment by jmcarp** [comment]
Ready for edits @brittag !

**Review by cnelson — APPROVED** [review]

**Pull request merged**
