### PR TITLE
[WIP] - Credhub import documentation

### PR DESCRIPTION
**Pull request by jontours**
This documentation is mostly done.  Leaving space for comment on adding directions for a possible bulk credential import file generation, but I think as is, this is the best way to go.  As it would be a more deliberate and careful process (i.e. we really want to ensure credential types are correct).

### CODE REVIEW

**Comment by mogul** [comment]
@mxplusb and @jontours is this old PR still relevant, particularly given work Mike was doing to make the bulk import tool work?

**Comment by eddietejeda** [comment]
@jontours Is this documentation relevant to the change you just made?

**Comment by karareinsel** [comment]
@jontours is this still relevant? If it's not, let's close it.

**Comment by siennathesane** [comment]
This is still relevant, @jontours and I worked on dev today, and tomorrow is production.

**Comment by karareinsel** [comment]
@mxplusb - did this go into production?

**Comment by siennathesane** [comment]
Docs? I haven't written any documentation around this. At some point, before we set up Concourse with this, we should.

**Comment by karareinsel** [comment]
@mxplusb will take a look at the PR and hopefully this issue can be closely out soon.

**Review by siennathesane — APPROVED** [review]

**Pull request merged**
