### PR TITLE
Initial production ready page

### PR DESCRIPTION
**Pull request by dlapiduz**

### CODE REVIEW

**Comment by afeld** [comment]
@jroo and I had been talking about lists like this... https://pages.18f.gov/before-you-ship/ is the closest thing I know of, but did we end up finding anything else?

/cc @yozlet @mbland

**Comment by afeld** [comment]
@monfresh Had you been working on anything like this?

**Comment by mbland** [comment]
@leahbannon and @hollyallen and I also had a chat about this stuff a week or so back.

**Comment by dlapiduz** [comment]
@mogul put together an interesting list here: https://trello.com/c/8o8LQrbI/273-checklist-of-devops-best-practices-for-app-teams-with-cloud-gov-specfics

**Comment by mogul** [comment]
That Trello card comes out of us consulting with the PICC team (including @hollyallen) on operational readiness ahead of the launch. It's not a list of requirements, but rather a "what good looks like" list from which teams can generate stories in their backlog and make conscious decisions about what they want done before they launch.

I'm thinking now that the list in that Trello card is going to end up as a pull-request that adds a new page on pages.18f.gov and puts a reference to it in that before-you-ship document. Does that sound good? Then later we'll amend it with a link to how each can be accomplished in cloud.gov for those using it. (Links would go to the planned cloud.gov "Common Patterns" section, with a page on each.)

Since I'm still new and reluctant to just go asserting stuff like this on pages.18f.gov... Sound good? Anyone want to help?

**Comment by afeld** [comment]
Ok, apparently @leahbannon has been working on this as well:

https://docs.google.com/document/d/1rw01PX_NPeOK13sThLqI3EPyNwYijD0BJDUGQTdlDpA/edit

Was going to say "I can't even keep track anymore", but her list seems to be the most comprehensive.

@mogul I think before-you-ship can contain both the hard and soft requirements (as long as the distinction is made clear), but don't feel super strongly about it.

**Comment by mogul** [comment]
I went over Leah's list with her yesterday and helped firm up some stuff, and she helped me sift through my list for the actual requirements (not just "good"), which are now bolded in that Trello card. So we're kind of working the problem from both sides. I'm not ready to pull that card yet (eg actually do the work to get it all guide-like, cross-linked, etc.) because the story scope as-is includes "point out how it's done using cloud.gov", but feel free to refer people to it or drop a temporary link to it in before-you-ship if you like.

**Comment by hollyallen** [comment]
I agree with the approach of doing all this in a cross linked fashion.

On Sat, Sep 5, 2015 at 8:54 AM, Bret Mogilefsky notifications@github.com
wrote:

> I went over Leah's list with her yesterday and helped firm up some stuff,
> and she helped me sift through my list for the actual requirements (not
> just "good"), which are now bolded in that Trello card. So we're kind of
> working the problem from both sides. I'm not ready to pull that card yet
> (eg actually do the work to get it all guide-like, cross-linked, etc.)
> because the story scope as-is includes "point out how it's done using
> cloud.gov", but feel free to refer people to it or drop a temporary link
> to it in before-you-ship if you like.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/cloud-foundry-notes/pull/92#issuecomment-137970511
> .

## 

Holly Allen
Product Lead | 18F
holly.allen@gsa.gov | 415-917-8421

**Comment by dlapiduz** [comment]
@mogul and everyone else should we merge this or close it for now? I think that having _something_ is better than nothing.

I think that _before-you-ship_ should be split into "compliance" (as in a law/reg requires it), "18f technical requirements", "18f best practices" (18f doesn't require it but likes it) and "cloud.gov best practices" (I don't think we should **require** anything)

**Comment by leahbannon** [comment]
@dlapiduz Do you think those 4 categories are in descending order of importance? As a PM user, breaking that list into priority order is most important to me. You might merge the 18F and cloud dot gov best practices category.

**Comment by dlapiduz** [comment]
To me they are in descending order but that doesn't mean that something
that is a cloud.gov best practice doesn't end in the 18f requirements. Does
that make sense?

On Monday, September 14, 2015, Leah Bannon notifications@github.com wrote:

> @dlapiduz https://github.com/dlapiduz Do you think those 4 categories
> are in descending order of importance? As a PM user, breaking that list
> into priority order is most important to me. You might merge the 18F and
> cloud dot gov best practices category.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/cloud-foundry-notes/pull/92#issuecomment-140109192
> .

## 

Diego Lapiduz
diego.lapiduz@gsa.gov
(415) 730-5945

**Comment by mogul** [comment]
I agree with merging this as-is for now, with expectations for improvements later... We have a story coming up (that I think will explode into a bunch of small stories) which is specifically about documenting cloud.gov-based best practices, and we can improve it then!

**Comment by dlapiduz** [comment]
:+1:

**Pull request merged**
