### PR TITLE
Add quickstart promo on homepage, fixed typo

### PR DESCRIPTION
**Pull request by femmebot**
Added content on homepage to point to tutorials. Also corrected a typo — congratulatons (sic) — on  the quickstart page.

screencapture-localhost-1313-1512581353713

### CODE REVIEW

**Comment by pburkholder** [comment]
> Tour cloud.gov with our <a href="/quickstart">quickstart guide</a> to create an account and deploy a sample app in your own free sandbox. You can follow along with videos from our latest workshop, or take a self-guided tutorial in one of our supported programming languages.

My attempt....

**Review by gboone — DISMISSED** [review]

**Comment by gboone** [comment]
I'll take a crack at it. Trying to get the site to build locally right now (it worked fine yesterday!)

**Review by gboone — APPROVED** [review]

**Comment by gboone** [comment]
@femmebot I revised that sentence and this looks good to me. Thanks for putting this together. @pburkholder you want to do the honors and merge this one?

**Comment by brittag** [comment]
Checked this out locally and it looks good to me too, so I merged it!

**Pull request merged**
