### PR TITLE
Use `{%-` to reduce whitespace

### PR DESCRIPTION
**Pull request by pburkholder**
Per @ccostino finding [https://mathieubuisson.github.io/reducing-whitespace-jekyll-html/](https://mathieubuisson.github.io/reducing-whitespace-jekyll-html/)

this change reduces a sample page , configuration-management, from
102kb to 44kb.

## Changes proposed in this pull request:

- Use Liquid templating tags with `-` to reduce whitespace
-

:sunglasses:[PREVIEW URL](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/peterb/bye-blanks)

## Security Considerations

None

### CODE REVIEW

**Comment by ccostino** [comment]
Well that definitely got rid of the blank lines and such in the source, but it seems to have broken the sidebar somewhat:

Screen Shot 2020-10-07 at 11 49 17 AM

**Comment by karareinsel** [comment]
No hollow bullets in the side navigation.

**Comment by pburkholder** [comment]
This looks pretty good to me how that I restored some of the white space in HTML.  

Check out https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/peterb/bye-blanks/docs/management/plugins/ and click around especially in team docs (where the nesting was most recently fixed).

**Comment by ccostino** [comment]
This definitely looks better to me now, thanks @pburkholder!  When you update the branch I can do a final review. :-)

**Comment by pburkholder** [comment]
@ccostino I hope it stays stable long enough to check it out...

**Review by mheadd — APPROVED** [review]
I clicked around for a bit in the preview site, and viewed source to make sure the whitespace wasn't there any longer - it doesn't appear to be. Looks good to me, @pburkholder.

**Pull request merged**
