### PR TITLE
Update pricing.md

### PR DESCRIPTION
**Pull request by RonWilliams**
Add new pricing for ES / Redis brokered service.

## Changes proposed in this pull request:
-
-
-

:sunglasses:[PREVIEW URL](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/master)

## Security Considerations
[Note the any security considerations here, or make note of why there are none]

### CODE REVIEW

**Comment by mheadd** [comment]
Did the Federalist build on this fail?

**Comment by karareinsel** [comment]
@mheadd I think so - the preview URL doesn't show any CSS.

**Comment by ccostino** [comment]
Ah that's because this was done as a fork to the repo, instead of as a new branch on the repo itself.

**Review by ChrisMcGowan — APPROVED** [review]
LGTM

**Pull request merged**
