### PR TITLE
Update name of Slack channel in docs

### PR DESCRIPTION
**Pull request by jessieay**
- #g-devops is archived
- New channel is just called "devops"

### CODE REVIEW

**Comment by mogul** [comment]
Actually even that is out of date... It's now #cloud-gov-support...

**Comment by jessieay** [comment]
@mogul woah! will update.

**Comment by dlapiduz** [comment]
@jessieay do you still want to take a stab at it?

**Comment by jessieay** [comment]
@dlapiduz updated!

**Pull request merged**
