### PR TITLE
Fix CI to correctly handle new content for link checking

### PR DESCRIPTION
**Pull request by markdboyd**
When we add new content to this repo, it won't actually appear on the cloud.gov website until the PR is merged. But our CI workflow to check for broken links was scanning the website HTML files assuming that the content would exist on cloud.gov. Thus the broken links scanning would fail anytime we added new content to this repo.

## Changes proposed in this pull request:

To fix the above issue, I made the following changes

- Integrated a Github action to detect when new files have been added to the repo
- Wrote a script to wait on the Federalist preview build in CI
- Added Jekyll config for Github branch name used in content edit links
- If new files have been added to the repo, then the CI workflow will:
  - Wait on the Federalist build
  - Build the website files using the URL for the Federalist preview build and current branch name
- If no new files have been added to the repo, then the CI workflow will build the website files using the default Jekyll configuration 

:sunglasses:[PREVIEW URL](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/fix-link-checking-new-content)

## Security Considerations

None

### CODE REVIEW

**Review by apburnes — APPROVED** [review]
This would be cool to abstract this into a published GH action that other Federalist users could leverage. 💯

**Comment by mheadd** [comment]
Agree with @apburnes - would love to see this as a standalone GH action. Nice work!

**Comment by markdboyd** [comment]
@apburnes I agree with that. I assume you're talking about just abstracting the part that waits on a Federalist build?

**Comment by apburnes** [comment]
@markdboyd exactly

**Pull request merged**
