### PR TITLE
Fix <br /> elements

### PR DESCRIPTION
**Pull request by mogul**
## Changes proposed in this pull request:
- Fix bad XML in <br /> elements.

:sunglasses:[PREVIEW URL](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/BRANCH_NAME)

## Security Considerations
None, this is a text change in presentational markup.

### CODE REVIEW

**Comment by bengerman13** [comment]
Thanks @mogul. You probably remember this from last time, but Federalist will only build branches from contributors, so I'm going to pull your PR into a new branch and make a PR from that :)

**Comment by bengerman13** [comment]
see #1967

**Comment by mogul** [comment]
Yup. Let me know if there's a way I can contribute that's less effort for you to accept.

**Comment by bengerman13** [comment]
:+1: you're doing it the easiest way I can imagine. Thanks for taking the time to fix this stuff when you see it!

**Pull request merged**
