### PR TITLE
Add logo in PNG format to use outside of the site

### PR DESCRIPTION
**Pull request by dlapiduz**

### CODE REVIEW

**Review by afeld — APPROVED** [review]

**Comment by brittag** [comment]
Hm, this doesn't quite match the logo that's on our homepage now.

**Comment by thisisdano** [comment]
Maybe this is something that should live in `cg-design` instead?

**Comment by thisisdano** [comment]
Ready for review in `cg-design`: https://github.com/18F/cg-design/pull/23

**Comment by dlapiduz** [comment]
I just did an SVG to PNG conversion and I guess it didn't go well :)

Thanks @thisisdano

**Pull request merged**
