### PR TITLE
Add open data plan

### PR DESCRIPTION
**Pull request by dlapiduz**

### CODE REVIEW

**Comment by dlapiduz** [comment]
What do you think @berndverst @mogul @nikzei ?

**Comment by mogul** [comment]
Looks fine to me; you double-checked it with a bunch of folks who are likely customers of it, right?

**Comment by berndverst** [comment]
@dlapiduz I don't understand this.

The account is limited to 2 GB memory usage per month? Would those 2 GB be included?

Are you saying $10k fee and you get up to $2500 in resources which could be 2 GB of memory or other services?

**Comment by dlapiduz** [comment]
@berndverst no, to make this clear I used the same language as all the other plans but added the "limit" to the plan description and the services fees.

**Review by berndverst — APPROVED** [review]

**Pull request merged**
