### PR TITLE
added gtm script and IDs for tracking

### PR DESCRIPTION
**Pull request by femmebot**
Added Google Tag Manager script to track homepage events for customer list section.

### CODE REVIEW

**Comment by pburkholder** [comment]
What URL provided guidance on how to set this up and use it? It'd be good to have for reference here in the PR. 

Also, you've added a `tag-manager-body.html` but I don't see it referenced anywhere (but I'm probably missing something obvious).

**Comment by mogul** [comment]
@femmebot can you respond to @pburkholder's questions? (I'm not sure I'm qualified to review/merge this one.)

**Comment by brittag** [comment]
We should also [do a bit of compliance work](https://gsa-tts.slack.com/archives/C0A1Z7L2U/p1508956994000692) before we merge in new URLs that fall into the "Cross-Domain JavaScript Source File Inclusion" category.

**Comment by brittag** [comment]
Noting for the record that compliance work is in progress for this change! We just have to wait for a compliance approval and then we can approve and merge this.

**Comment by brittag** [comment]
@femmebot Should we close this one now that https://github.com/18F/cg-site/pull/1190 is merged? Is it redundant?

**Comment by brittag** [comment]
Closing since I assume that this is redundant with https://github.com/18F/cg-site/pull/1190 - feel free to reopen if I'm wrong. :)

**Pull request closed without merging**
