### PR TITLE
[WIP] Document custom domain service.

### PR DESCRIPTION
**Pull request by jmcarp**
Much like the code, the docs for the alb-backed custom domain service are a copy and paste of the cdn broker, modified to take out the cdn parts. We should probably also explain when users should pick each broker.

### CODE REVIEW

**Comment by brittag** [comment]
Josh and I worked on this together and it now reflects my understanding of the compliance impact.

**Review by mogul — APPROVED** [review]
LGTM. Any reason it's still considered [WIP], or should it be merged?

**Comment by jmcarp** [comment]
We haven't shipped the feature yet. Otherwise, this should be good to go.

**Review by timothy-spencer — APPROVED** [review]
LGTM, though probably should wait on merging until it's out in production.

**Comment by mogul** [comment]
@brittag are we waiting on 3PAO review to put the custom domain broker into production, or can it go now?

**Comment by brittag** [comment]
@mogul It can go into production as soon as it's ready.

**Pull request merged**
