### PR TITLE
Quickstart redux: additional tutorials

### PR DESCRIPTION
**Pull request by femmebot**
Added other non-video tutorial content. (See https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-10036) 

screencapture-localhost-1313-quickstart-1511793606527

screencapture-localhost-1313-quickstart-1511793623170

screencapture-localhost-1313-quickstart-1511793634121

### CODE REVIEW

**Comment by pburkholder** [comment]
This is very cool!

I think I'd like to roll with this with the following changes:

Video tutorials:

- [ ]  The download CLI link should have the same buttons as the Java app

Java app:
- [ ]  Needs a little work to make it clear what to expect at each step

Hello worlds:
- [ ]  Let's change this to a Python or PHP or .Net walkthrough. Whichever one would be most likely to work with our customers.

I'm up for working on this.

**Comment by pburkholder** [comment]
We'll want this https://github.com/18F/cf-hello-worlds/pull/42 so the 3rd set of tutorials work.

**Comment by pburkholder** [comment]
I just pushed up a bunch of changes. Let's discuss on Monday.

**Review by gboone — DISMISSED** [review]

**Comment by pburkholder** [comment]
@gboone Sorry I pushed up one more change and now it needs a new review. Can you help with that?

**Review by pburkholder — APPROVED** [review]

**Pull request merged**
