### PR TITLE
rearrange menu sections

### PR DESCRIPTION
**Pull request by afeld**
The biggest change in this pull request moves all the navigation items previously under Docs -> Operations to a Contributing section of the menu. The Contributing section is really intended for cloud.gov staff, but @mogul suggested the word "Contributing", which I think makes it more welcoming than something like "Internal Docs". Totally open to other ideas for the menu/sub-menu titles.

There are no content changes – just navigational. See commits for more specifics.

**Before**

screen shot 2015-12-27 at 9 55 17 am

**After**

screen shot 2015-12-24 at 11 27 50 am

/cc @jameshupp

### CODE REVIEW

**Comment by mogul** [comment]
@jameshupp What do you think? I'm fine with this if you are... Go ahead and merge if so.

**Comment by jameshupp** [comment]
This looks cool to me, with the one caveat that the distinction `Contributing > Deployment` vs. `Usage > Deploying Apps` is not obvious to me. The distinction is probably better understood to developers, so I think it's fine. But if you _do_ think this is potentially confusing, consider further modifying "Deployment" under Contributing. Are you contributing to what we deploy, how we deploy, how users deploy, etc.?

To reiterate, if this is already clear to people with the skills required to actually manage apps in cloud.gov, the existing PR is fine.

**Comment by afeld** [comment]
Hmm. The distinction is between people using the platform vs people running (or generally wanting to help with) the platform. The latter could arguably be a whole different (section of the) site, but I don't think we want to make that split right now. "Usage" and "Contributing" are fairly common verbs(?) corresponding to two groups in the open source world, but I am totally open to other ideas.

Will merge later today if there are no suggestions...easy to change it later if we have an epiphany.

**Comment by dlapiduz** [comment]
what do you all think about moving the "contributing" outside of the main "docs" site?

**Comment by jameshupp** [comment]
@afeld I get that, and I think it's perfectly good. Just wanted to flag because of proximity.

**Comment by afeld** [comment]
@dlapiduz I don't think it's a bad idea, but I say we keep that discussion separate. If the plan is still to merge the landing page and the docs site, I think it could just be a subsection of the site, just like the user docs would be.

**Pull request merged**
