### PR TITLE
add a page around setting up custom domains

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by afeld** [comment]
Still working on it, and I'm sure there are more specific instructions needed for different scenarios that I haven't thought of (slash don't understand).

**Comment by konklone** [comment]
Ready for merge, or are you still working on it?

**Comment by afeld** [comment]
Happy to PR the rest separately if what's there looks good – your call!

**Comment by afeld** [comment]
Wahoo it worked! https://cap.18f.us

**Pull request merged**
