### PR TITLE
Expect protected branches and required reviews

### PR DESCRIPTION
**Pull request by mogul**
This states our intent that GitHub PRs are required to have an explicit review before merging.

DO NOT MERGE until we are sure this is turned back on... See [discussion in #cloud-gov-atlas](https://gsa-tts.slack.com/archives/cloud-gov-atlas/p1475816934002711)

/cc @NoahKunin

### CODE REVIEW

**Comment by sharms** [comment]
The following `cg-*` repositories have enabled protected branches and required reviews:

```
git@github.com:18F/cg-docs.git
git@github.com:18F/cg-manifests.git
git@github.com:18F/cg-harden-boshrelease.git
git@github.com:18F/cg-scripts.git
git@github.com:18F/cg-quotas-db.git
git@github.com:18F/cg-cf-release.git
git@github.com:18F/cg-secureproxy-boshrelease.git
git@github.com:18F/cg-dashboard.git
git@github.com:18F/cg-landing.git
git@github.com:18F/cg-metrics.git
git@github.com:18F/cg-uaa.git
git@github.com:18F/cg-sandbox-bot.git
git@github.com:18F/cg-compliance.git
git@github.com:18F/cg-release.git
git@github.com:18F/cg-stats-scripts.git
git@github.com:18F/cg-pipelines.git
git@github.com:18F/cg-style.git
git@github.com:18F/cg-style-gem.git
git@github.com:18F/cg-deploy-concourse-docker-image.git
git@github.com:18F/cg-goshin.git
git@github.com:18F/cg-deploy-compliance-documentation.git
git@github.com:18F/cg-pipeline-tasks.git
git@github.com:18F/cg-deploy-monitoring.git
git@github.com:18F/cg-deploy-concourse.git
git@github.com:18F/cg-grafana-boshrelease.git
git@github.com:18F/cg-deploy-cf.git
git@github.com:18F/cg-influxdb-boshrelease.git
git@github.com:18F/cg-deploy-discourse.git
git@github.com:18F/cg-collectd-boshrelease.git
git@github.com:18F/cg-common-resource.git
git@github.com:18F/cg-deploy-logsearch.git
git@github.com:18F/cg-s3-service-broker.git
git@github.com:18F/cg-riemann-boshrelease.git
git@github.com:18F/cg-deploy-admin-ui.git
git@github.com:18F/cg-deploy-influxdb-firehose-nozzle.git
git@github.com:18F/cg-deploy-bosh.git
git@github.com:18F/cg-nessus-agent-boshrelease.git
git@github.com:18F/cg-product.git
git@github.com:18F/cg-application-ssp-example.git
git@github.com:18F/cg-atlas.git
git@github.com:18F/cg-ossec-boshrelease.git
git@github.com:18F/cg-tripwire-boshrelease.git
git@github.com:18F/cg-uaa-release.git
git@github.com:18F/cg-uaa-invite.git
git@github.com:18F/cg-provision.git
git@github.com:18F/cg-agent-q.git
git@github.com:18F/cg-encrypt-blobstore-boshrelease.git
git@github.com:18F/cg-design.git
git@github.com:18F/cg-bootstrap-concourse-ami.git
git@github.com:18F/cg-awslogs-boshrelease.git
git@github.com:18F/cg-deploy-bots.git
git@github.com:18F/cg-deploy-docker-swarm.git
git@github.com:18F/cg-clamav-boshrelease.git
git@github.com:18F/cg-nessus-manager-boshrelease.git
git@github.com:18F/cg-deploy-nessus-manager.git
git@github.com:18F/cg-riemannc-boshrelease.git
git@github.com:18F/cg-newrelic-boshrelease.git
git@github.com:18F/cg-snort-boshrelease.git
git@github.com:18F/cg-deploy-diego.git
git@github.com:18F/cg-fake-uaa.git
git@github.com:18F/cg-deploy-riemann-firehose-nozzle.git
git@github.com:18F/cg-deploy-kubernetes.git
git@github.com:18F/cg-migration-bot.git
git@github.com:18F/cg-diagrams.git
git@github.com:18F/cg-sast-docker-image.git
git@github.com:18F/cg-deploy-aws-light-stemcell-builder.git
```

**Comment by sharms** [comment]
The following repos were not in scope or had permissions issues:

```
!git@github.com:18F/cg-cron.git
!git@github.com:18F/cg-s3-proxy.git
!git@github.com:18F/cg-postmortems.git
!git@github.com:18F/cg-deck-docker-images.git
```

**Comment by mogul** [comment]
@NoahKunin, I think this is ready for review+merge now.

**Review by NoahKunin — COMMENTED** [review]
It's no longer clear to me that Code Climate is a complete solution.

Does it scan for vulnerabilities on dependencies?
Does Nessus, if not?

If no to both, we need to keep working on this.

**Review by NoahKunin — CHANGES_REQUESTED** [review]
I hit the wrong button, I'm requesting changes.

**Comment by NoahKunin** [comment]
Answered my Q. It does not. My question about Nessus is open-ended, since we've never even allowed Nessus to scan something that wasn't already fully patched. Unblocking this and we can circle back on the dependency issue.

**Review by NoahKunin — APPROVED** [review]

**Pull request merged**
