### PR TITLE
Fix table alignment

### PR DESCRIPTION
**Pull request by mogul**
This is just a stop-gap until major styling of the docs is done.

### CODE REVIEW

**Comment by msecret** [comment]
Does this actually work? I didn't think you could specify percentages as html attributes. But if it works then this is fine.

**Comment by NoahKunin** [comment]
@msecret %s will work as HTML attributes (at least it does in Chrome). 

The problem is the use of `valign`. That's not a real property. The correct property is called `vertical-align`. The current edit there won't do anything.

**Comment by mogul** [comment]
That's weird, because it works fine locally in Chrome:
image

`valign` is the HTML attribute equivalent of `vertical-align` in CSS... Maybe that's what you're thinking of. 

Are you guys actually seeing this not work locally, or are you just guessing it will not work based on the code?

**Comment by msecret** [comment]
Just guessing.

**Comment by NoahKunin** [comment]
I actually did throw it in the console and got an error for `valign` - now I see why. Page is supposed to be conformant to HTML5, and `valign` was deprecated.

**Pull request merged**
