### PR TITLE
validate HTML links

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by dlapiduz** [comment]
@afeld you are adding a Ruby dependency to this clean and neat project?!?! Also we have wercker for CI, do you mind making it work there instead of Travis?

**Comment by afeld** [comment]
> you are adding a Ruby dependency to this clean and neat project?!?!

Good point – I'll use Perl instead :trollface: 

http://www.rollyson.org/posts/checking-hugo-content-for-dead-links/

> we have wercker for CI

18F uses _all_ the CI systems :unamused: Done!

**Comment by dlapiduz** [comment]
It doesn't like that we have private links: https://app.wercker.com/#buildstep/550c8327108eee7f44035192

Also, since you are using the step we can just ignore all the Ruby stuff in this repo... :trollface: ^2

**Comment by afeld** [comment]
> It doesn't like that we have private links

:rage1: 

Yeah, [the step](https://github.com/kyleboyle/html-proofer-test#todo) doesn't support the html-proofer arguments yet #nowitsmyproblem #howtoderailaidansfocus

> we can just ignore all the Ruby stuff in this repo

Only if you don't care about running it locally!

**Comment by dlapiduz** [comment]
@afeld since you don't do anything else, you can just fork the step and add the commands...

**Comment by afeld** [comment]
I've been using [cross-references](http://gohugo.io/extras/crossreferences/) recently...the syntax is a little weird/verbose, but they are nice in that internal links are validated by the build itself.

**Comment by afeld** [comment]
Ok, got the build working, though there are broken links. Will work on fixing them before we merge.

https://app.wercker.com/#buildstep/56845ff7f80ab39d220b9414

**Comment by afeld** [comment]
Rebased, with links fixed.

https://app.wercker.com/#buildstep/56857110b1b23faa6602185b

**Pull request merged**
