### PR TITLE
recommend the good_migrations gem for Rails apps

### PR DESCRIPTION
**Pull request by afeld**
Just learned about this gem through http://blog.testdouble.com/posts/2016-02-05-good-migrations.html, and I've been bitten by the problem enough to recommend it across the board.

/cc @monfresh #36

### CODE REVIEW

**Comment by jessieay** [comment]
this is a great idea! and will certainly keep me in check. I recently referenced AR in a migration and it completely failed when running on production a month or two later because of some additional migrations we'd added in the meantime.

**Comment by jessieay** [comment]
one question: should this be somewhere else instead? I don't usually think to look at cloud.gov docs for info on how to build good software (although right now I am not sure which of our guides I would look at, tbh, since there are so many), usually just look here when I am trying to debug something with a deploy.

**Comment by afeld** [comment]
Open to ideas! Could certainly see a section of https://pages.18f.gov/before-you-ship/ being dedicated to general good production practices for frameworks, but we don't have that yet.

**Comment by monfresh** [comment]
Since this is specific to Rails, I think this would fit well into a Rails best practices guide, which could be a separate page under our development guide. I've been meaning to get a Rails guide started. I'll submit an initial draft this week.

**Comment by afeld** [comment]
I say we merge this here, then move it if a better place avails itself.

**Comment by monfresh** [comment]
I tried the gem a while back and it didn't do what I expected it to. See https://github.com/testdouble/good-migrations/issues/5 

Have you actually tried the gem and gotten it to fail a migration? 

I wouldn't want to recommend a gem that we haven't confirmed is useful.

**Comment by afeld** [comment]
I don't really have any Rails apps I'm working on to test it with...can't remember if I did so at the time either, sorry! We can close if we don't feel confident in it.

**Comment by dlapiduz** [comment]
Going to close this, if we have the opportunity to test further, lets revisit it.

**Pull request closed without merging**
