### PR TITLE
Update govcloud invitation URL

### PR DESCRIPTION
**Pull request by LinuxBozo**
The invite app has evolved. This means that it provides more than just invitation functionality. As such, the app has a new URL, and there is an invite endpoint. This PR addresses those changes.

@rogeruiz @brittag

### CODE REVIEW

**Comment by brittag** [comment]
This seems ok from a content perspective, but it's ended up with a merge conflict. Also not sure whether we should have a redirect from the old URL to the new URL, in case people have bookmarked the old one?

**Comment by LinuxBozo** [comment]
@brittag this should have merge conflicts solved now.

**Comment by brittag** [comment]
Thanks! I'll merge, since my question about redirects is separate from getting this updated in the docs. :)

**Review by brittag — APPROVED** [review]

**Comment by brittag** [comment]
Ohh I've now run into a confusing bug with the new URL, so I'm no longer sure I should merge this. I'll file it separately.

**Comment by brittag** [comment]
@LinuxBozo here's what I'm running into: https://github.com/18F/cg-product/issues/529

**Comment by brittag** [comment]
Merging since those concerns have been resolved. Hooray!!!!

**Pull request merged**
