### PR TITLE
Remove "Federalist Migration" from Pages portion of the cloud.gov website

### PR DESCRIPTION
**Pull request by svenaas**
Addressing #2298 

## Changes proposed in this pull request:
- Removed "Federalist Migration" link from top nav in /pages section of the website
- Removed page "Federalist Migration" (/pages/federalist-migration/) 
- Redirected /pages/federalist-migration/ to /pages/

:sunglasses:[PREVIEW URL](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/2298-remove-federalist-migration)

## Security Considerations
None. This is a content change to remove content which is no longer needed.

### CODE REVIEW

**Comment by drewbo** [comment]
@apburnes do we have any policy on keeping a redirect up for deleted pages? I think we linked to this page a few times in our newsletter

**Comment by apburnes** [comment]
No specific policy but we could add a client side redirect to point to `cloud.gov/pages`

**Comment by svenaas** [comment]
> No specific policy but we could add a client side redirect to point to `cloud.gov/pages`

@apburnes, by client side in this case do you mean using `jekyll-redirect-from`?

**Comment by apburnes** [comment]
Yup

**Review by apburnes — APPROVED** [review]
🪓

**Pull request merged**
