### PR TITLE
Org Managers / System Owners should request memory quota changes + explain sandbox case

### PR DESCRIPTION
**Pull request by brittag**
We should make sure memory quota change requests come from somebody who can likely authorize billing changes.

### CODE REVIEW

**Review by fureigh — DISMISSED** [review]
Thanks, for this, @brittag!

One question: where would I check whether the requester is a System Owner? The only roles I see in Cloud Foundry are `Org Manager`, `Billing Manager` and `Org Auditor`.

And a minor copy editing nitpick: I'd change `since` to `as` because this isn't time-related.

**Comment by mogul** [comment]
@fureigh: Info about the System Owner is captured as part of the customer info in https://customers.fr.cloud.gov

**Comment by mogul** [comment]
Just found out that the system owner isn't recorded in that service yet. Will edit to point to the right place.

**Comment by mogul** [comment]
@fureigh care to approve?

**Review by el-mapache — APPROVED** [review]
This is great, super helpful!

**Comment by brittag** [comment]
@el-mapache Thanks! Go ahead and merge if it looks good to you; it doesn't need additional review unless you think somebody else needs to look at it.

**Comment by fureigh** [comment]
@mogul @brittag LGTM! Thanks!

**Pull request merged**
