### PR TITLE
Re-purpose and expand code-review for configuration management plan

### PR DESCRIPTION
**Pull request by LinuxBozo**
@dlapiduz Pretty sure this satisfies #283 

@brittag For your review as well.

### CODE REVIEW

**Comment by dlapiduz** [comment]
@LinuxBozo I think we need a section on "What should go into config management" (everything), "How is config management tested" etc.

Here are the notes from the follow ups:

```
All changes to a configuration needs to go to GitHub
GitHub changes need to be peer reviewed before accepted
Changes need to be deployed to a staging environment, tested for functionality and security before pushing to production
Tools should revert to known configurations if there are any unauthorized changes to the environment
Secrets should be uploaded to a file 
```

**Comment by dlapiduz** [comment]
I know this covers the need peer review part

**Comment by dlapiduz** [comment]
I think most of it is there... we just need to spell it out a bit more

**Comment by LinuxBozo** [comment]
@dlapiduz Ping. Made more changes that I think addresses everything now.

**Pull request merged**
