### PR TITLE
Add syntax highlighting with Highlight JS

### PR DESCRIPTION
**Pull request by rogeruiz**
cc @jmcarp

### CODE REVIEW

**Comment by rogeruiz** [comment]
@jmcarp actually ~~hold off on this one for now. I have to update the `package.json` as well~~ never mind. `^2.4.0` should cover `2.6.2`

**Comment by rogeruiz** [comment]
Will help make docs more legible for operators for the work involved in #879

**Comment by jmcarp** [comment]
We could also copy the highlight styles from `node_modules` in `build-css` if we don't feel like vendoring #justsaying

**Review by LinuxBozo — APPROVED** [review]
:shipit:

**Comment by rogeruiz** [comment]
PRs welcome @jmcarp 😆  :trollface:

**Pull request merged**
