### PR TITLE
Add guidance for customers on CP and IR plans

### PR DESCRIPTION
**Pull request by brittag**
This is based on an email I wrote to a customer a while back, along with [our own exercise template](https://docs.google.com/document/d/1diCaE4SkJE1QHz8bqy6XFFw-dSxMLHsEkvxvgYKKUwg/edit#).

### CODE REVIEW

**Comment by Bryanthales-zz** [comment]
Reviewed document and recommended minor changes.

**Comment by karareinsel** [comment]
@bryanthales can you advise if this is done, blocked, or in progress?

**Comment by karareinsel** [comment]
Tagging @Bryanthales to confirm the latest status of this issue.

**Comment by Bryanthales-zz** [comment]
> Tagging @Bryanthales to confirm the latest status of this issue.

I reviewed and provided my recommendations before Britta departed --- crux of it is I prefer to have guidance generic and not filled out so that users can understand that the guidance is applicable to several different scenarios; whereas Britta preferred to have a detailed example in the guidance. Neither is the correct or wrong way, just a difference in approach. I would recommend that @RonWilliams review and decide which path he prefers. Then we can implement the changes and close the card.

**Comment by karareinsel** [comment]
@ronwilliams - I think this is just waiting on your review and then it can be closed out.

**Comment by RonWilliams** [comment]
@Bryanthales I'm comfortable with the broad / generalized approach. If customer feedback pushes for specific examples, we can reconsider.

**Review by hillaryj — APPROVED** [review]

**Pull request merged**
