### PR TITLE
[WIP] Troubleshooting TLS/SSL certificate issues with CDN

### PR DESCRIPTION
**Pull request by adborden**
This includes a guide for troubleshooting TLS/SSL certificate issues while creating custom domain services or CDN services. Still work to do and a few placeholders.

Todo
- [ ] consolidate troubleshooting steps on the custom domain and CDN service pages if necessary.
- [ ] Add example about querying for TXT records.

### CODE REVIEW

**Comment by siennathesane** [comment]
@adborden if you're willing to finalize this, I'll review it for you.

**Comment by adborden** [comment]
@mxplusb can you provide me with some CDN service output that I can include as an example? I think I'm held up because I can't create additional examples with only a prototyping account. For example, i can't create a CDN route.

**Comment by adborden** [comment]
@mxplusb if you can provide support for this, I am happy to take it over the finish line.

**Comment by siennathesane** [comment]
@adborden we're in the process of changing the broker right now, this will definitely be relevant in the not so distant future.

**Comment by adborden** [comment]
@mxplusb were the CDN broker changes done?

**Comment by siennathesane** [comment]
@adborden not immediately, no. @spgreenberg can you please take a look at this and determine it's viability? Thanks.

**Pull request closed without merging**
