### PR TITLE
Fix cache mismatch pagination issue

### LINKED ISSUE #2096: Page title rendering incorrectly
The page title for the `News` section is incorrectly displayed as `cloud.gov knowledge base`. More info in [this Slack thread](https://gsa-tts.slack.com/archives/GNSL334HM/p1650301651354339). 

Screen Shot 2022-04-18 at 2 42 03 PM

### PR DESCRIPTION
**Pull request by hursey013**
## Changes proposed in this pull request:
- Prevents cached layout from being used for paginated collections
- This bug can be observed currently when visiting https://cloud.gov/news/ - observe that the title of the page is `cloud.gov knowledge base` since it is using the cached version

Closes #2096 

## Security Considerations
None

### CODE REVIEW

**Comment by markdboyd** [comment]
Closes #2096

**Review by mheadd — DISMISSED** [review]
👍 🙌 🇺🇸

**Comment by hursey013** [comment]
Added a quick comment about the patch for future reference: https://github.com/cloud-gov/cg-site/compare/e896525a7ab24b847983d90db71b740628695d5d..077de997f44717f8c83fc31f66096c544b2b4b04

**Review by markdboyd — APPROVED** [review]

**Comment by markdboyd** [comment]
LGTM

**Pull request merged**
