### PR TITLE
Create a micro site out of the docs

### PR DESCRIPTION
**Pull request by dlapiduz**
Lets hugo this thing...

### CODE REVIEW

**Comment by dlapiduz** [comment]
@ozzyjohnson @kaitlin ping

**Comment by dlapiduz** [comment]
The site is up at https://docs.cf.18f.us

**Comment by afeld** [comment]
It's forcing me to HTTPS but then giving me a cert error...is this expected?

**Comment by afeld** [comment]
Also the site is AWESOME. Well done, sir!

**Comment by dlapiduz** [comment]
@afeld this is the same old cf SSL issue. Until we have a domain we can't
get a wildcard SSL.

**Pull request merged**
