### PR TITLE
update docs for zero-downtime-deploy

### PR DESCRIPTION
**Pull request by afomi**

### CODE REVIEW

**Review by bengerman13 — APPROVED** [review]
👍

**Comment by jontours** [comment]
We might want to actually try testing this before merging, but I agree with the changes.

**Comment by afomi** [comment]
I have working commits to reference. Happy to chat.

> https://github.com/GSA/touchpoints/pull/16

**Comment by siennathesane** [comment]
I'm fine with it since it's a `cf` CLI subcommand.

**Comment by bengerman13** [comment]
Thanks @afomi!

**Pull request merged**
