### PR TITLE
Style staging menu

### PR DESCRIPTION
**Pull request by jcscottiii**
The beginning of the side bar for the docs.
image

Needs https://github.com/18F/cg-style/pull/7

### CODE REVIEW

**Comment by jcscottiii** [comment]
Not finished at all. Need to abide by the [style guide](https://github.com/18F/cg-style/blob/master/documentation/frontend_standards.md). most notable thing everywhere is undo the nesting (it's everywhere lol). Will do in next commit.
cc: @msecret

**Comment by msecret** [comment]
Let me know if you wanna go over strategy on the nesting. Also, is there a PR in cg-style to go along with this?

**Comment by jcscottiii** [comment]
Needs https://github.com/18F/cg-style/pull/7

**Comment by dlapiduz** [comment]
can we merge this?

**Comment by dlapiduz** [comment]
do you have it deployed somewhere?

**Comment by jcscottiii** [comment]
Not yet. rebasing now. and stuff kinda broke.

image

**Pull request merged**
