### PR TITLE
Update to remove HTTP only comment

### PR DESCRIPTION
**Pull request by coobr01**
## Changes proposed in this pull request:
- Just a .md update because HTTPS is actually available when using the HTTP option to access an s3 bucket  (i.e. outside of using the s3 protocol itself).

## Security Considerations
None.

### CODE REVIEW

**Review by onelittlebecca — APPROVED** [review]

**Comment by bengerman13** [comment]
@coobr01 thanks for the PR. Has this changed recently? 
 The [docs from AWS](https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html) indicate https is not available on bucket websites.

**Comment by coobr01** [comment]
Not sure, all I can say is that its working in an s3 service instance that I recently created under my Cloud.gov org/space for my app.

image

**Comment by bengerman13** [comment]
I see - that request is going to the API endpoint `<bucket>.s3-<region>.amazonaws.com`, not the website endpoint `<bucket>.s3-website-<region>.amazonaws.com`. With public objects, like in this bucket, the API will behave pretty similarly to a website, but [with some differences](https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html#WebsiteRestEndpointDiff)

I believe the bucket you're looking at has website hosting disabled, but I tested on a bucket with hosting enabled and I'm not able to connect via HTTPS.

**Comment by coobr01** [comment]
Ok, i would close this PR without merging then, thanks.

**Comment by bengerman13** [comment]
Thanks @coobr01

**Comment by onelittlebecca** [comment]
Good catch -- I missed that <facepalm>

**Pull request closed without merging**
